/* export const PRODUCTS_SERVICE = 'PRODUCTS_SERVICE';
export const USERS_SERVICE = 'USERS_SERVICE';
export const PAYMENTS_SERVICE = 'PAYMENTS_SERVICE'; */
export const NATS_SERVICE = 'NATS_SERVICE';
